platform :ios, '11.0'
use_frameworks!

target 'CanvasToolbar_Example' do
  pod 'CanvasToolbar', :path => '../'
  pod 'PKHUD', '~> 5.0'

  target 'CanvasToolbar_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
